CrestronIP="192.168.0.200"
Port="41792"
Password="1234"

[[Devices]]
Name="Island"
Room="Kitchen"
ID=12
Up=514
Down=515
Type="analog"

[[Devices]]
Name="OverCounter"
Room="Kitchen"
ID=13
Up=516
Down=517
Type="analog"

[[Devices]]
Name="UnderCabinet"
Room="Kitchen"
ID=14
Up=518
Down=519
Type="analog"

[[Devices]]
Name="BaseFront"
Room="Basement"
ID=54
Up=558
Down=559
Type="analog"

[[Devices]]
Name="Rear"
Room="Basement"
ID=31
Up=560
Down=561
Type="analog"

[[Devices]]
Name="Front"
Room="Outdoor"
ID=17
Up=524
Down=525
Type="analog"

[[Devices]]
Name="Amp"
Room="Kitchen"
ID=20
CTRLON=[15,30,31,13]
CTRLOFF=[30,31,26]
Type="digital"
StateString="Apple TV"

[[Devices]]
Name="KitchenHigh"
Room="Kitchen"
ID=453
Type="digital"